/*

Andrey Fernandez Garcia - RM: 87219
Diego Augusto da Cruz - RM 86877
Emily Keyt Manfrin - RM: 87198
Giovana Nelo Furlan - RM: 88936
João Victor de Jesus Martins Silva - RM: 89087
Pedro Henrique Santos Modesto Delmondes - RM: 86719

*/


INSERT INTO endorf_usuario (id_usuario,nm_usuario,dt_nascimento,dt_cadastro,ds_email,ds_senha) VALUES
(sq_endorf_usuario.NEXTVAL,'MARIA',TO_DATE('13/09/2000','DD/MM/YYYY'),TO_DATE('09/09/2020','DD/MM/YYYY'),'MA@GMAIL.COM','12345A');
INSERT INTO endorf_usuario (id_usuario,nm_usuario,dt_nascimento,dt_cadastro,ds_email,ds_senha) VALUES
(sq_endorf_usuario.NEXTVAL,'VANDA',TO_DATE('01/01/1980','DD/MM/YYYY'),TO_DATE('07/07/2020','DD/MM/YYYY'),'ANA@GMAIL.COM','82345B');
INSERT INTO endorf_usuario (id_usuario,nm_usuario,dt_nascimento,dt_cadastro,ds_email,ds_senha) VALUES
(sq_endorf_usuario.NEXTVAL,'VANDERSON',TO_DATE('03/05/1988','DD/MM/YYYY'),TO_DATE('19/09/2020','DD/MM/YYYY'),'VAN@GMAIL.COM','72345D');
INSERT INTO endorf_usuario (id_usuario,nm_usuario,dt_nascimento,dt_cadastro,ds_email,ds_senha) VALUES
(sq_endorf_usuario.NEXTVAL,'VANDERLEI',TO_DATE('08/06/1997','DD/MM/YYYY'),TO_DATE('15/10/2020','DD/MM/YYYY'),'VANDERLEI@GMAIL.COM','72345D');
INSERT INTO endorf_usuario (id_usuario,nm_usuario,dt_nascimento,dt_cadastro,ds_email,ds_senha) VALUES
(sq_endorf_usuario.NEXTVAL,'ANTONIO',TO_DATE('02/02/1992','DD/MM/YYYY'),TO_DATE('12/10/2020','DD/MM/YYYY'),'ANTONIO@GMAIL.COM','72345D');
INSERT INTO endorf_usuario (id_usuario,nm_usuario,dt_nascimento,dt_cadastro,ds_email,ds_senha) VALUES
(sq_endorf_usuario.NEXTVAL,'BEATRIZ',TO_DATE('12/03/1993','DD/MM/YYYY'),TO_DATE('14/11/2020','DD/MM/YYYY'),'BEATRIZ@GMAIL.COM','72345D');
INSERT INTO endorf_usuario (id_usuario,nm_usuario,dt_nascimento,dt_cadastro,ds_email,ds_senha) VALUES
(sq_endorf_usuario.NEXTVAL,'VANESSA',TO_DATE('05/05/1995','DD/MM/YYYY'),TO_DATE('11/01/2021','DD/MM/YYYY'),'VANESSA@GMAIL.COM','72345D');
INSERT INTO endorf_usuario (id_usuario,nm_usuario,dt_nascimento,dt_cadastro,ds_email,ds_senha) VALUES
(sq_endorf_usuario.NEXTVAL,'ANDRESSA',TO_DATE('02/02/1992','DD/MM/YYYY'),TO_DATE('12/12/2020','DD/MM/YYYY'),'ANDRESSA@GMAIL.COM','72345D');
INSERT INTO endorf_usuario (id_usuario,nm_usuario,dt_nascimento,dt_cadastro,ds_email,ds_senha) VALUES
(sq_endorf_usuario.NEXTVAL,'ANA',TO_DATE('09/10/2002','DD/MM/YYYY'),TO_DATE('08/09/2020','DD/MM/YYYY'),'ANA@GMAIL.COM','72345D');
INSERT INTO endorf_usuario (id_usuario,nm_usuario,dt_nascimento,dt_cadastro,ds_email,ds_senha) VALUES
(sq_endorf_usuario.NEXTVAL,'ANABEL',TO_DATE('01/11/2001','DD/MM/YYYY'),TO_DATE('01/07/2020','DD/MM/YYYY'),'ANABEL@GMAIL.COM','72345D');




INSERT INTO endorf_profi (id_profissional,nm_profissional,dt_nascimento,dt_cadastro,ds_email,ds_senha) VALUES
(sq_endorf_profi.NEXTVAL,'MABEL',TO_DATE('02/01/1991','DD/MM/YYYY'),TO_DATE('14/12/2020','DD/MM/YYYY'),'MABEL@GMAIL.COM','42345D');
INSERT INTO endorf_profi (id_profissional,nm_profissional,dt_nascimento,dt_cadastro,ds_email,ds_senha) VALUES
(sq_endorf_profi.NEXTVAL,'NAYARA',TO_DATE('01/03/1993','DD/MM/YYYY'),TO_DATE('13/01/2021','DD/MM/YYYY'),'NAY@GMAIL.COM','72345D');
INSERT INTO endorf_profi (id_profissional,nm_profissional,dt_nascimento,dt_cadastro,ds_email,ds_senha) VALUES
(sq_endorf_profi.NEXTVAL,'MARIANA',TO_DATE('06/06/1986','DD/MM/YYYY'),TO_DATE('17/01/2021','DD/MM/YYYY'),'MARIANA@GMAIL.COM','82345F');
INSERT INTO endorf_profi (id_profissional,nm_profissional,dt_nascimento,dt_cadastro,ds_email,ds_senha) VALUES
(sq_endorf_profi.NEXTVAL,'MIGUEL',TO_DATE('04/03/1987','DD/MM/YYYY'),TO_DATE('19/04/2021','DD/MM/YYYY'),'MIGUEL@GMAIL.COM','62345H');
INSERT INTO endorf_profi (id_profissional,nm_profissional,dt_nascimento,dt_cadastro,ds_email,ds_senha) VALUES
(sq_endorf_profi.NEXTVAL,'ANABEL',TO_DATE('01/05/1975','DD/MM/YYYY'),TO_DATE('15/02/2021','DD/MM/YYYY'),'ANABEL@GMAIL.COM','42345B');
INSERT INTO endorf_profi (id_profissional,nm_profissional,dt_nascimento,dt_cadastro,ds_email,ds_senha) VALUES
(sq_endorf_profi.NEXTVAL,'PEDRO',TO_DATE('03/03/1972','DD/MM/YYYY'),TO_DATE('12/01/2021','DD/MM/YYYY'),'PEDRO@GMAIL.COM','22345F');
INSERT INTO endorf_profi (id_profissional,nm_profissional,dt_nascimento,dt_cadastro,ds_email,ds_senha) VALUES
(sq_endorf_profi.NEXTVAL,'MARCUS',TO_DATE('01/03/1979','DD/MM/YYYY'),TO_DATE('19/02/2021','DD/MM/YYYY'),'MARCUS@GMAIL.COM','42345K');
INSERT INTO endorf_profi (id_profissional,nm_profissional,dt_nascimento,dt_cadastro,ds_email,ds_senha) VALUES
(sq_endorf_profi.NEXTVAL,'VANESSA',TO_DATE('19/08/1976','DD/MM/YYYY'),TO_DATE('15/09/2020','DD/MM/YYYY'),'VANESSA@GMAIL.COM','62345I');
INSERT INTO endorf_profi (id_profissional,nm_profissional,dt_nascimento,dt_cadastro,ds_email,ds_senha) VALUES
(sq_endorf_profi.NEXTVAL,'JOANA',TO_DATE('12/02/1989','DD/MM/YYYY'),TO_DATE('14/10/2020','DD/MM/YYYY'),'JOANA@GMAIL.COM','72345P');
INSERT INTO endorf_profi (id_profissional,nm_profissional,dt_nascimento,dt_cadastro,ds_email,ds_senha) VALUES
(sq_endorf_profi.NEXTVAL,'EVERALDO',TO_DATE('19/08/1969','DD/MM/YYYY'),TO_DATE('15/01/2021','DD/MM/YYYY'),'EVERALDO@GMAIL.COM','62345P');   




INSERT INTO endorf_end (id_end,nm_rua,nr_numero,nr_cep,nm_bairro,nm_cidade,nm_estado,id_usuario) VALUES
(sq_endorf_end.NEXTVAL,'AV.DOS BANDERANTES',22,03645010,'VILA DAS CARMÉLIAS','SÃO PAULO','SP',8);
INSERT INTO endorf_end (id_end,nm_rua,nr_numero,nr_cep,nm_bairro,nm_cidade,nm_estado,id_usuario) VALUES
(sq_endorf_end.NEXTVAL,'AV.DOS IMPERADOR',38,07545010,'VILA ITÚ','SÃO PAULO','SP',2);
INSERT INTO endorf_end (id_end,nm_rua,nr_numero,nr_cep,nm_bairro,nm_cidade,nm_estado,id_usuario) VALUES
(sq_endorf_end.NEXTVAL,'AV.DAS AMÉRICAS',987,08685010,'VILA IMPERADOR','SÃO PAULO','SP',6);
INSERT INTO endorf_end (id_end,nm_rua,nr_numero,nr_cep,nm_bairro,nm_cidade,nm_estado,id_usuario) VALUES
(sq_endorf_end.NEXTVAL,'AV.DOS ITÚ',654,01645610,'VILA DAS BANDEIRAS','SÃO PAULO','SP',7);
INSERT INTO endorf_end (id_end,nm_rua,nr_numero,nr_cep,nm_bairro,nm_cidade,nm_estado,id_usuario) VALUES
(sq_endorf_end.NEXTVAL,'AV.DOS OTÁ',123,05445910,'SÃO MIGUEL','SÃO PAULO','SP',5);
INSERT INTO endorf_end (id_end,nm_rua,nr_numero,nr_cep,nm_bairro,nm_cidade,nm_estado,id_usuario) VALUES
(sq_endorf_end.NEXTVAL,'AV.DOS AHANGUERA',222,03645010,'VILA AMÉRICA','SÃO PAULO','SP',4);
INSERT INTO endorf_end (id_end,nm_rua,nr_numero,nr_cep,nm_bairro,nm_cidade,nm_estado,id_profissional) VALUES
(sq_endorf_end.NEXTVAL,'RUA JÃO JOAO',132,04546010,'VILA IMPERADOR','MINAS GERAIS','MG',4);
INSERT INTO endorf_end (id_end,nm_rua,nr_numero,nr_cep,nm_bairro,nm_cidade,nm_estado,id_profissional) VALUES
(sq_endorf_end.NEXTVAL,'RUA OTÁ',32,02346010,'VILA IMPATÁ','SÃO PAULO','SP',2);
INSERT INTO endorf_end (id_end,nm_rua,nr_numero,nr_cep,nm_bairro,nm_cidade,nm_estado,id_profissional) VALUES
(sq_endorf_end.NEXTVAL,'RUA MANTU',2,04344010,'VILA ROMANA','SÃO JOSÉ DOS CAMPOS','SP',3);
INSERT INTO endorf_end (id_end,nm_rua,nr_numero,nr_cep,nm_bairro,nm_cidade,nm_estado,id_profissional) VALUES
(sq_endorf_end.NEXTVAL,'RUA IMPATÁ',342,03647010,'VILA ITÚ','SÃO SEBASTIÃO','SP',2);



INSERT INTO endorf_video (id_video,id_profissional,dt_postagem,nr_visualizacoes,nr_duracao) VALUES
(sq_endorf_video.NEXTVAL,2,TO_DATE('19/08/2021','DD/MM/YYYY'),8,180);
INSERT INTO endorf_video (id_video,id_profissional,dt_postagem,nr_visualizacoes,nr_duracao) VALUES
(sq_endorf_video.NEXTVAL,3,TO_DATE('12/09/2021','DD/MM/YYYY'),5,90);
INSERT INTO endorf_video (id_video,id_profissional,dt_postagem,nr_visualizacoes,nr_duracao) VALUES
(sq_endorf_video.NEXTVAL,4,TO_DATE('29/08/2021','DD/MM/YYYY'),3,120);
INSERT INTO endorf_video (id_video,id_profissional,dt_postagem,nr_visualizacoes,nr_duracao) VALUES
(sq_endorf_video.NEXTVAL,5,TO_DATE('15/09/2021','DD/MM/YYYY'),4,110);
INSERT INTO endorf_video (id_video,id_profissional,dt_postagem,nr_visualizacoes,nr_duracao) VALUES
(sq_endorf_video.NEXTVAL,6,TO_DATE('19/10/2021','DD/MM/YYYY'),1,60);
INSERT INTO endorf_video (id_video,id_profissional,dt_postagem,nr_visualizacoes,nr_duracao) VALUES
(sq_endorf_video.NEXTVAL,9,TO_DATE('23/07/2021','DD/MM/YYYY'),9,160);
INSERT INTO endorf_video (id_video,id_profissional,dt_postagem,nr_visualizacoes,nr_duracao) VALUES
(sq_endorf_video.NEXTVAL,7,TO_DATE('09/10/2021','DD/MM/YYYY'),19,120);
INSERT INTO endorf_video (id_video,id_profissional,dt_postagem,nr_visualizacoes,nr_duracao) VALUES
(sq_endorf_video.NEXTVAL,8,TO_DATE('14/11/2020','DD/MM/YYYY'),15,260);
INSERT INTO endorf_video (id_video,id_profissional,dt_postagem,nr_visualizacoes,nr_duracao) VALUES
(sq_endorf_video.NEXTVAL,2,TO_DATE('19/12/2020','DD/MM/YYYY'),13,340);
INSERT INTO endorf_video (id_video,id_profissional,dt_postagem,nr_visualizacoes,nr_duracao) VALUES
(sq_endorf_video.NEXTVAL,10,TO_DATE('09/11/2020','DD/MM/YYYY'),9,120);




INSERT INTO endorf_tel (id_tel,id_usuario,id_profissional,nr_numero,nr_ddd,nr_ddi) VALUES
(sq_endorf_tel.NEXTVAL,2,10,28765643,11,55);
INSERT INTO endorf_tel (id_tel,id_usuario,id_profissional,nr_numero,nr_ddd,nr_ddi) VALUES
(sq_endorf_tel.NEXTVAL,3,9,958765643,11,55);
INSERT INTO endorf_tel (id_tel,id_usuario,id_profissional,nr_numero,nr_ddd,nr_ddi) VALUES
(sq_endorf_tel.NEXTVAL,3,8,29565643,11,55);
INSERT INTO endorf_tel (id_tel,id_usuario,id_profissional,nr_numero,nr_ddd,nr_ddi) VALUES
(sq_endorf_tel.NEXTVAL,4,7,929565643,11,55);
INSERT INTO endorf_tel (id_tel,id_usuario,id_profissional,nr_numero,nr_ddd,nr_ddi) VALUES
(sq_endorf_tel.NEXTVAL,5,6,26565643,11,55);
INSERT INTO endorf_tel (id_tel,id_usuario,id_profissional,nr_numero,nr_ddd,nr_ddi) VALUES
(sq_endorf_tel.NEXTVAL,6,5,29865643,11,55);
INSERT INTO endorf_tel (id_tel,id_usuario,id_profissional,nr_numero,nr_ddd,nr_ddi) VALUES
(sq_endorf_tel.NEXTVAL,7,5,939565643,11,55);
INSERT INTO endorf_tel (id_tel,id_usuario,id_profissional,nr_numero,nr_ddd,nr_ddi) VALUES
(sq_endorf_tel.NEXTVAL,8,4,934565643,11,55);
INSERT INTO endorf_tel (id_tel,id_usuario,id_profissional,nr_numero,nr_ddd,nr_ddi) VALUES
(sq_endorf_tel.NEXTVAL,9,3,956565643,11,55);
INSERT INTO endorf_tel (id_tel,id_usuario,id_profissional,nr_numero,nr_ddd,nr_ddi) VALUES
(sq_endorf_tel.NEXTVAL,10,10,28565643,11,55);



INSERT INTO endorf_hobby (id_hobby,nm_hobby) VALUES
(sq_endorf_hobby.NEXTVAL,'CULINÁRIA');
INSERT INTO endorf_hobby (id_hobby,nm_hobby) VALUES
(sq_endorf_hobby.NEXTVAL,'DANÇA');
INSERT INTO endorf_hobby (id_hobby,nm_hobby) VALUES
(sq_endorf_hobby.NEXTVAL,'ESPORTE');
INSERT INTO endorf_hobby (id_hobby,nm_hobby) VALUES
(sq_endorf_hobby.NEXTVAL,'IOGA');
INSERT INTO endorf_hobby (id_hobby,nm_hobby) VALUES
(sq_endorf_hobby.NEXTVAL,'CULINÁRIA');
INSERT INTO endorf_hobby (id_hobby,nm_hobby) VALUES
(sq_endorf_hobby.NEXTVAL,'ESPORTE');
INSERT INTO endorf_hobby (id_hobby,nm_hobby) VALUES
(sq_endorf_hobby.NEXTVAL,'ESPORTE');
INSERT INTO endorf_hobby (id_hobby,nm_hobby) VALUES
(sq_endorf_hobby.NEXTVAL,'IOGA');
INSERT INTO endorf_hobby (id_hobby,nm_hobby) VALUES
(sq_endorf_hobby.NEXTVAL,'CULINÁRIA');
INSERT INTO endorf_hobby (id_hobby,nm_hobby) VALUES
(sq_endorf_hobby.NEXTVAL,'ESPORTE');



INSERT INTO endorf_hobby_usuario (id_hobby,id_usuario) VALUES
(10,2);
INSERT INTO endorf_hobby_usuario (id_hobby,id_usuario) VALUES
(9,3);
INSERT INTO endorf_hobby_usuario (id_hobby,id_usuario) VALUES
(8,4);
INSERT INTO endorf_hobby_usuario (id_hobby,id_usuario) VALUES
(7,5);
INSERT INTO endorf_hobby_usuario (id_hobby,id_usuario) VALUES
(6,6);
INSERT INTO endorf_hobby_usuario (id_hobby,id_usuario) VALUES
(5,5);
INSERT INTO endorf_hobby_usuario (id_hobby,id_usuario) VALUES
(4,4);
INSERT INTO endorf_hobby_usuario (id_hobby,id_usuario) VALUES
(3,3);
INSERT INTO endorf_hobby_usuario (id_hobby,id_usuario) VALUES
(2,2);
INSERT INTO endorf_hobby_usuario (id_hobby,id_usuario) VALUES
(10,3);
INSERT INTO endorf_hobby_usuario (id_hobby,id_usuario) VALUES
(9,5);
INSERT INTO endorf_hobby_usuario (id_hobby,id_usuario) VALUES
(8,6);
INSERT INTO endorf_hobby_usuario (id_hobby,id_usuario) VALUES
(9,7);
INSERT INTO endorf_hobby_usuario (id_hobby,id_usuario) VALUES
(7,8);
INSERT INTO endorf_hobby_usuario (id_hobby,id_usuario) VALUES
(6,2);
INSERT INTO endorf_hobby_usuario (id_hobby,id_usuario) VALUES
(5,3);
INSERT INTO endorf_hobby_usuario (id_hobby,id_usuario) VALUES
(4,5);
INSERT INTO endorf_hobby_usuario (id_hobby,id_usuario) VALUES
(5,4);
INSERT INTO endorf_hobby_usuario (id_hobby,id_usuario) VALUES
(8,3);
INSERT INTO endorf_hobby_usuario (id_hobby,id_usuario) VALUES
(10,9);



INSERT INTO endorf_hobby_profi (id_hobby,id_profissional) VALUES
(10,1);
INSERT INTO endorf_hobby_profi (id_hobby,id_profissional) VALUES
(9,2);
INSERT INTO endorf_hobby_profi (id_hobby,id_profissional) VALUES
(8,3);
INSERT INTO endorf_hobby_profi (id_hobby,id_profissional) VALUES
(7,4);
INSERT INTO endorf_hobby_profi (id_hobby,id_profissional) VALUES
(6,5);
INSERT INTO endorf_hobby_profi (id_hobby,id_profissional) VALUES
(7,6);
INSERT INTO endorf_hobby_profi (id_hobby,id_profissional) VALUES
(6,7);
INSERT INTO endorf_hobby_profi (id_hobby,id_profissional) VALUES
(5,8);
INSERT INTO endorf_hobby_profi (id_hobby,id_profissional) VALUES
(4,9);
INSERT INTO endorf_hobby_profi (id_hobby,id_profissional) VALUES
(3,10);
INSERT INTO endorf_hobby_profi (id_hobby,id_profissional) VALUES
(1,1);
INSERT INTO endorf_hobby_profi (id_hobby,id_profissional) VALUES
(10,4);
INSERT INTO endorf_hobby_profi (id_hobby,id_profissional) VALUES
(10,9);
INSERT INTO endorf_hobby_profi (id_hobby,id_profissional) VALUES
(9,10);
INSERT INTO endorf_hobby_profi (id_hobby,id_profissional) VALUES
(8,5);
INSERT INTO endorf_hobby_profi (id_hobby,id_profissional) VALUES
(5,10);
INSERT INTO endorf_hobby_profi (id_hobby,id_profissional) VALUES
(6,2);
INSERT INTO endorf_hobby_profi (id_hobby,id_profissional) VALUES
(8,10);
INSERT INTO endorf_hobby_profi (id_hobby,id_profissional) VALUES
(9,1);
INSERT INTO endorf_hobby_profi (id_hobby,id_profissional) VALUES
(3,5);



INSERT INTO endorf_usuario_profi (id_usuario,id_profissional) VALUES
(2,10);
INSERT INTO endorf_usuario_profi (id_usuario,id_profissional) VALUES
(3,9);
INSERT INTO endorf_usuario_profi (id_usuario,id_profissional) VALUES
(4,8);
INSERT INTO endorf_usuario_profi (id_usuario,id_profissional) VALUES
(5,7);
INSERT INTO endorf_usuario_profi (id_usuario,id_profissional) VALUES
(6,6);
INSERT INTO endorf_usuario_profi (id_usuario,id_profissional) VALUES
(7,5);
INSERT INTO endorf_usuario_profi (id_usuario,id_profissional) VALUES
(6,4);
INSERT INTO endorf_usuario_profi (id_usuario,id_profissional) VALUES
(8,3);
INSERT INTO endorf_usuario_profi (id_usuario,id_profissional) VALUES
(9,2);
INSERT INTO endorf_usuario_profi (id_usuario,id_profissional) VALUES
(10,1);
INSERT INTO endorf_usuario_profi (id_usuario,id_profissional) VALUES
(9,9);
INSERT INTO endorf_usuario_profi (id_usuario,id_profissional) VALUES
(8,2);
INSERT INTO endorf_usuario_profi (id_usuario,id_profissional) VALUES
(7,9);
INSERT INTO endorf_usuario_profi (id_usuario,id_profissional) VALUES
(6,5);
INSERT INTO endorf_usuario_profi (id_usuario,id_profissional) VALUES
(2,4);
INSERT INTO endorf_usuario_profi (id_usuario,id_profissional) VALUES
(10,2);
INSERT INTO endorf_usuario_profi (id_usuario,id_profissional) VALUES
(9,6);
INSERT INTO endorf_usuario_profi (id_usuario,id_profissional) VALUES
(3,7);
INSERT INTO endorf_usuario_profi (id_usuario,id_profissional) VALUES
(9,5);
INSERT INTO endorf_usuario_profi (id_usuario,id_profissional) VALUES
(8,9);

COMMIT;
