/*

Andrey Fernandez Garcia - RM: 87219
Diego Augusto da Cruz - RM 86877
Emily Keyt Manfrin - RM: 87198
Giovana Nelo Furlan - RM: 88936
João Victor de Jesus Martins Silva - RM: 89087
Pedro Henrique Santos Modesto Delmondes - RM: 86719

*/


DROP SEQUENCE sq_endorf_end;

DROP SEQUENCE sq_endorf_hobby;

DROP SEQUENCE sq_endorf_hobby_profi;   

DROP SEQUENCE sq_endorf_hobby_usuario;

DROP SEQUENCE sq_endorf_profi;

DROP SEQUENCE sq_endorf_tel;

DROP SEQUENCE sq_endorf_usuario;

DROP SEQUENCE sq_endorf_usuario_profi;

DROP SEQUENCE sq_endorf_video;