/*
Andrey Fernandez Garcia - RM: 87219
Diego Augusto da Cruz - RM 86877
Emily Keyt Manfrin - RM: 87198
Giovana Nelo Furlan - RM: 88936
João Victor de Jesus Martins Silva - RM: 89087
*/

DROP TABLE t_doacao_venda CASCADE CONSTRAINTS;

DROP TABLE t_endereco CASCADE CONSTRAINTS;

DROP TABLE t_produto CASCADE CONSTRAINTS;

DROP TABLE t_supermercados CASCADE CONSTRAINTS;

DROP TABLE t_telefone CASCADE CONSTRAINTS;

DROP SEQUENCE SQ_T_SUPERPERMERCADO CASCADE CONSTRAINTS;

DROP SEQUENCE SQ_T_TELEFONE CASCADE CONSTRAINTS;

DROP SEQUENCE SQ_T_ENDEREÇO CASCADE CONSTRAINTS;

DROP SEQUENCE SQ_T_DOACAO_VENDA CASCADE CONSTRAINTS;

DROP SEQUENCE SQ_T_PRODUTO CASCADE CONSTRAINTS;